### ISSUE TITLE
Create TODO

### ISSUE THREAD

**Issue by macht13** [macht13/tasker#2]
# Basic TODO creation
- [ ] have syntax for creation
- [ ] parse fields correctly
- [ ] store in database
