### ISSUE TITLE
TODO projects

### ISSUE THREAD

**Issue by macht13** [macht13/tasker#3]
# Group TODOs into projects
- [ ] add project field
- [ ] store current projects
- [ ] be able to list current projects
